import { Metadata } from 'next';
import React from 'react'

export const metadata: Metadata = {
    title: "Contact",
    description: "Generated by create next app",
};

const page = () => {
    console.log("object")
    return (
        <div className="max-w-md mx-auto my-10 p-6 bg-gray-800 rounded-md shadow-md">
            <h2 className="text-xl font-semibold mb-4 text-gray-100">Contact Us</h2>
            <form>
                <div className="mb-4">
                    <label htmlFor="name" className="block text-sm font-medium text-gray-100">
                        Your Name
                    </label>
                    <input type="text" id="name" name="name" className="mt-1 p-2 w-full bg-gray-700 text-gray-100 border rounded-md" />
                </div>
                <div className="mb-4">
                    <label htmlFor="email" className="block text-sm font-medium text-gray-100">
                        Your Email
                    </label>
                    <input type="email" id="email" name="email" className="mt-1 p-2 w-full bg-gray-700 text-gray-100 border rounded-md" />
                </div>
                <div className="mb-4">
                    <label htmlFor="message" className="block text-sm font-medium text-gray-100">
                        Message
                    </label>
                    <textarea id="message" name="message" rows={4} className="mt-1 p-2 w-full bg-gray-700 text-gray-100 border rounded-md" />
                </div>
                <button type="submit" className="bg-blue-500 text-white px-4 py-2 rounded-md hover:bg-blue-600">
                    Submit
                </button>
            </form>
        </div>
    )
}

export default page
