// pages/portfolio.tsx
import React from 'react';
import { Metadata } from 'next';
import ProjectCard from '@/components/ProjectCard';

const projects = [
    {
        title: 'Project 1',
        description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit.',
        imageUrl: 'https://via.placeholder.com/500x300',
    },
    {
        title: 'Project 2',
        description: 'Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
        imageUrl: 'https://via.placeholder.com/500x300',
    },
    {
        title: 'Project 3',
        description: 'Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
        imageUrl: 'https://via.placeholder.com/500x300',
    },
];

export const metadata: Metadata = {
    title: "Portfolio",
    description: "Generated by create next app",
};

const page = () => {
    return (
        <div className="container mx-auto p-4">
            <h1 className="text-3xl font-semibold mb-6">Portfolio</h1>
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
                {projects.map((project, index) => (
                    <ProjectCard key={index} {...project} />
                ))}
            </div>
        </div>
    );
};

export default page;
